### ISSUE TITLE
Check rule 'Do not leave unused definitions'.

### ISSUE THREAD

**Issue by bhaskarmelkani** [zalando-incubator/zally#261] opened 2017-04-11 15:44 UTC
Swagger Schema: [Github Link](https://gist.github.com/bhaskarmelkani/d1781a848e88747039ff7e56d287db18).

It has a definition that is used, but validating the schema gives 'SHOULD – Do not leave unused definitions'.

**Comment by mkulak** [comment] 2017-04-11 19:26
@bhaskarmelkani
```
            schema: 
              type: "object"
              items: 
                $ref: "#/definitions/Pet"
``` 
The problem is that `items` is normally used to describe arrays. For objects you have to use `properties`. At least this is what I understand from reading [spec](http://swagger.io/specification/#itemsObject):
```
items	Items Object	Required if type is "array". Describes the type of items in the array.
```
Spec is really hard for me to read so I'm not 100% sure.
Also all examples use "items" for arrays and "properties" for object.
Also our parser parses this response as literally empty ObjectProperty (no properties, no other fields):
![empty](https://lh3.googleusercontent.com/gcVeOLDttKWNHJmkbmY4PCixHvKAOaPj1XfUdMzlJXcnmTezqry7zc8hNT82kNQ34iA2PREbP75JYMnXCLXO2JKkNyZiFCI1-qeqZdFCJmALD_DSlLyTGOkRR4fduQdRIhNRK28Z0aUjopJ62u7ANZlHDU7dnxRCifxVxjgGYzubG5YfqucTGOevz-yZult2EqSIY-tEpNBZLVIYg3haKjugvC2S7dH_4G2t7gZ_LJ8bPvyl6Z6QnQBp0mbTp8uIxiL7mnyAeQhJMjXWWhlzy2zO5ljA_XjJpgTniS7KXxGvAxZgcei7jt9fRabVilX6qGjD5-Kr525uScJZXoKFxbUgvOF4eVWAdx9nAEHC9r31IelpmUNapaJPSWmxmInDO-hS_vZBmjyaqFBkAPPwIzl4dcFHEI8VwN_h7zPaesaxp-JGfF8aACCvVaiO50prOtolL59uqNCCxP04hDDtNj-myOQTqskGNzBMrhY56hbKj4iS6JDaQCWMnq8P9mkpYqk52W_L_PJtlD3135WlbiBkMdLdSfk8_FDTZMx1UTuUzxF-arubCxtAOmKWdp3tYOTzEsLOV02fdIhmCGUO0ZqqotEX-gxA8GLNQ4Ts9O80aYz8c58QLY5JD59dVUigLRYRzuh_aqHTpMfg9wMZfyGVmtqJ29tCRV9liR3FqMs=w990-h840-no)
So my bet that this swagger spec is invalid.

**Comment by bhaskarmelkani** [comment] 2017-04-11 20:36
@mkulak The example is a modified version of [Petstore Minimal](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore-minimal.yaml)

I have just changed the [type](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore-minimal.yaml#L30) to object else I was getting an error saying `MUST – Response As JSON Object`.

It was working fine earlier. @fmueller any thoughts on this ?

**Comment by mkulak** [comment] 2017-04-12 08:10
@bhaskarmelkani 
Original Perstore Minimal is not compliant with Zalando rules.
When you change type from "array" to "object" you should also change "items" to "properties". Otherwise your Swagger Spec is incorrect (at least in my current understanding of spec) for reasons I described in my previous comment.

**Comment by fmueller** [comment] 2017-04-12 08:13
I think @mkulak is right - objects have properties, arrays have items.

**Comment by mkulak** [comment] 2017-04-12 08:19
I will create separate issue for swagger validation. There is no sense in checking rules against invalid swagger. Not sure validation is feasible though, but at least we need to investigate it.

**Comment by fmueller** [comment] 2017-04-12 08:20
Sounds reasonable. I close this one.

**Closed by fmueller** 2017-04-12 08:20 UTC
Labels: question
